export default function TermsPage({ onBack }) {
  return (
    <div className="static-page">
      <button className="static-back" onClick={onBack}>← Back</button>
      <div className="static-content">
        <h1>Terms of Service & Privacy Policy</h1>
        <p className="static-date">Last updated: June 2026</p>

        <h2>1. About Adviserly</h2>
        <p>Adviserly is a free AI-powered advice platform. It is built and maintained by an independent developer and is not affiliated with any medical, legal, or financial institution.</p>

        <h2>2. AI Disclaimer</h2>
        <p>Adviserly uses artificial intelligence to provide general information and suggestions. The AI can make mistakes. All responses are for informational purposes only and should not replace professional advice from a licensed doctor, lawyer, financial advisor, or other certified professional.</p>

        <h2>3. Use at Your Own Risk</h2>
        <p>By using Adviserly, you agree that any actions you take based on AI responses are your own responsibility. We are not liable for any decisions made based on content generated by the AI.</p>

        <h2>4. No Account Required</h2>
        <p>Adviserly does not require you to create an account. No personal information is collected or stored on our servers.</p>

        <h2>5. Data & Privacy</h2>
        <p>We do not collect, store, or sell your personal data. Your chat conversations are processed by the Groq AI API to generate responses and are not permanently stored. Any data saved (like chat history or progress) is stored locally on your own device using browser storage.</p>

        <h2>6. Cookies</h2>
        <p>Adviserly uses browser localStorage only to save your preferences (language, tour status, saved chats). No tracking cookies or third-party analytics are used.</p>

        <h2>7. Third-Party Services</h2>
        <p>Adviserly uses the Groq AI API to power its responses. By using this service, your messages are sent to Groq's servers for processing. Please review Groq's privacy policy at groq.com for more information.</p>

        <h2>8. Support & Ko-fi</h2>
        <p>Clicking "Buy me a coffee" redirects you to Ko-fi, an independent platform. Any support is voluntary and appreciated but not required to use the service.</p>

        <h2>9. Changes</h2>
        <p>We may update these terms occasionally. Continued use of the platform means you accept any changes.</p>

        <h2>10. Contact</h2>
        <p>For questions or concerns, please reach out through the Support button on the website.</p>

        <div className="static-footer">
          Adviserly — AI advice for a better you. 💙
        </div>
      </div>
    </div>
  );
}
