export const SECTIONS = ["Wellness", "Daily Life", "Personal", "Tech"];

export const CATEGORIES = [
  {
    id: "general", icon: "💬", bg: "#1e2a38", section: "General",
    en: { name: "General Questions", label: "Ask me anything", chips: ["Give me a fun fact", "Help me decide something", "Explain something simply"] },
    tl: { name: "Pangkalahatang Tanong", label: "Magtanong ng kahit ano", chips: ["Bigyan mo ako ng fun fact", "Tulungan mo akong magdesisyon", "Ipaliwanag nang simple"] },
    prompt: "You are a helpful, knowledgeable, friendly general assistant. Ask ONE clarifying question if the topic is broad. Answer clearly with well-formatted paragraphs. If the user writes in Tagalog, respond in Tagalog.",
    followUp: "To give you the best answer — can you tell me a bit more about what you need?",
  },
  {
    id: "health", icon: "❤️", bg: "#3f0c0c", section: "Wellness",
    en: { name: "Health Advice", label: "Symptoms, wellness, nutrition", chips: ["What causes headaches?", "How to improve sleep?", "Is my diet balanced?"] },
    tl: { name: "Kalusugan", label: "Sintomas, kalusugan, nutrisyon", chips: ["Bakit masakit ang ulo ko?", "Paano mapabuti ang tulog?", "Malusog ba ang pagkain ko?"] },
    prompt: "You are a careful, empathetic health advisor. Ask ONE clarifying question before advising. Always remind users to see a doctor for serious concerns. If the user writes in Tagalog, respond in Tagalog.",
    followUp: "To help you better — how old are you roughly, and how long have you been experiencing this?",
  },
  {
    id: "skin", icon: "✨", bg: "#2a1a0f", section: "Wellness",
    en: { name: "Skin Care", label: "Routines, products, breakouts", chips: ["How to remove pimples?", "Best routine for oily skin", "What causes dark spots?"] },
    tl: { name: "Pag-aalaga ng Balat", label: "Rutina, produkto, pimples", chips: ["Paano aalisin ang pimples?", "Routine para sa mantikang balat", "Bakit may dark spots?"] },
    prompt: "You are a knowledgeable skincare advisor. Ask about skin type first. Give practical, evidence-based advice. If the user writes in Tagalog, respond in Tagalog.",
    followUp: "What's your skin type — oily, dry, combination, or sensitive?",
  },
  {
    id: "hair", icon: "💇", bg: "#1a0f2a", section: "Wellness",
    en: { name: "Hair Care", label: "Growth, styling, treatments", chips: ["How to reduce hair fall?", "Best shampoo for dry hair", "How to grow hair faster?"] },
    tl: { name: "Pag-aalaga ng Buhok", label: "Paglago, istilo, paggamot", chips: ["Paano mababawasan ang paglagas?", "Pinakamainam na shampoo", "Paano mapapabilis ang paglago?"] },
    prompt: "You are a hair care expert. Ask about hair type before giving advice. If the user writes in Tagalog, respond in Tagalog.",
    followUp: "What's your hair type — straight, wavy, or curly? And is it dry, oily, or normal?",
  },
  {
    id: "mental", icon: "🧠", bg: "#1a0a1a", section: "Wellness",
    en: { name: "Mental Wellness", label: "Stress, anxiety, motivation", chips: ["How to manage stress?", "I feel anxious lately", "How to stay motivated?"] },
    tl: { name: "Mental Wellness", label: "Stress, pagkabalisa, motibasyon", chips: ["Paano pamahalaan ang stress?", "Nangangamba ako", "Paano manatiling motivated?"] },
    prompt: "You are a compassionate mental wellness guide. Acknowledge feelings first, then ask ONE gentle clarifying question. Always recommend professional help for serious concerns. If the user writes in Tagalog, respond in Tagalog.",
    followUp: "I hear you — I'm here to help. Can you share a little more about what's been going on?",
  },
  {
    id: "fitness", icon: "💪", bg: "#0f1f04", section: "Wellness",
    en: { name: "Fitness", label: "Workouts, goals, nutrition", chips: ["Beginner workout at home", "How to lose belly fat?", "Best pre-workout food?"] },
    tl: { name: "Fitness", label: "Ehersisyo, goals, nutrisyon", chips: ["Workout para sa baguhan", "Paano mawalan ng tiyan?", "Pagkain bago mag-ehersisyo?"] },
    prompt: "You are an encouraging personal fitness coach. Ask about fitness level and goal before giving a plan. If the user writes in Tagalog, respond in Tagalog.",
    followUp: "Are you a complete beginner, somewhat active, or already working out regularly? And what's your main goal?",
  },
  {
    id: "cooking", icon: "🍳", bg: "#2a1a04", section: "Daily Life",
    en: { name: "Cooking Help", label: "Recipes, tips, substitutes", chips: ["Easy recipe with eggs", "Substitute for butter?", "How to cook rice perfectly?"] },
    tl: { name: "Pagluluto", label: "Mga recipe, tips, papalit", chips: ["Madaling recipe na may itlog", "Papalit sa butter?", "Paano magluto ng bigas?"] },
    prompt: "You are a friendly home cook. Ask what ingredients are available before suggesting recipes. If the user writes in Tagalog, respond in Tagalog.",
    followUp: "What ingredients do you have available? And any dietary restrictions?",
  },
  {
    id: "money", icon: "💰", bg: "#0a1f0a", section: "Daily Life",
    en: { name: "Money & Budget", label: "Saving, budgeting, expenses", chips: ["How do I start saving?", "50/30/20 rule explained", "Budget with low income?"] },
    tl: { name: "Pera at Budget", label: "Pag-iimpok, budget, gastos", chips: ["Paano magsimulang mag-ipon?", "Ipaliwanag ang 50/30/20 rule", "Budget sa maliit na kita?"] },
    prompt: "You are a friendly personal finance advisor for students and fresh graduates. Ask about income situation before giving advice. If the user writes in Tagalog, respond in Tagalog.",
    followUp: "Are you a student, fresh grad, or working? What's your current financial situation roughly?",
  },
  {
    id: "fashion", icon: "👗", bg: "#1f0f1f", section: "Daily Life",
    en: { name: "Fashion & Style", label: "Outfits, trends, confidence", chips: ["What to wear for an interview?", "Casual outfit ideas", "How to mix and match?"] },
    tl: { name: "Fashion at Estilo", label: "Outfit, trend, kumpiyansa", chips: ["Damit para sa interview?", "Casual outfit ideas", "Paano mag-mix and match?"] },
    prompt: "You are a friendly fashion advisor. Ask about occasion and style preference before suggesting outfits. If the user writes in Tagalog, respond in Tagalog.",
    followUp: "What's the occasion and what's your style vibe — casual, smart casual, or formal?",
  },
  {
    id: "relationship", icon: "💑", bg: "#2a0a1a", section: "Personal",
    en: { name: "Relationship Advice", label: "Love, friendship, family", chips: ["How to communicate better?", "I had a fight with my partner", "How to set boundaries?"] },
    tl: { name: "Relasyon at Payo", label: "Pag-ibig, pagkakaibigan, pamilya", chips: ["Paano mas mapabuti ang komunikasyon?", "Nag-away kami ng partner ko", "Paano mag-set ng boundaries?"] },
    prompt: "You are an empathetic relationship advisor. Acknowledge feelings first, then ask ONE clarifying question. Be non-judgmental and balanced. If the user writes in Tagalog, respond in Tagalog.",
    followUp: "That sounds tough. Can you tell me more about the situation so I can give you the most helpful advice?",
  },
  {
    id: "study", icon: "📖", bg: "#0a1428", section: "Personal",
    en: { name: "Study & School Help", label: "Exams, focus, learning tips", chips: ["How to study effectively?", "I can't focus while studying", "Best way to memorize?"] },
    tl: { name: "Pag-aaral at Paaralan", label: "Exam, focus, paraan ng pag-aaral", chips: ["Paano epektibong mag-aral?", "Hindi ako makapag-focus", "Pinakamainam na paraan ng memorize?"] },
    prompt: "You are a patient study coach. Ask about the subject and available time before giving study tips. If the user writes in Tagalog, respond in Tagalog.",
    followUp: "What subject or exam are you preparing for? And how much time do you have?",
  },
  {
    id: "career", icon: "💼", bg: "#0f1a0a", section: "Personal",
    en: { name: "Career & Job Tips", label: "Resume, interviews, growth", chips: ["How do I write a good resume?", "Tips for job interviews", "How to ask for a raise?"] },
    tl: { name: "Trabaho at Karera", label: "Resume, interview, paglago", chips: ["Paano gumawa ng magandang resume?", "Tips para sa job interview", "Paano humingi ng dagdag sa sahod?"] },
    prompt: "You are a helpful career advisor. Ask about industry and experience level before giving advice. If the user writes in Tagalog, respond in Tagalog.",
    followUp: "What field are you in or hoping to enter? And are you a fresh grad, career switcher, or looking to grow?",
  },
  {
    id: "pet", icon: "🐾", bg: "#1a1408", section: "Personal",
    en: { name: "Pet Care", label: "Dogs, cats, health & training", chips: ["How to train a puppy?", "My cat is not eating", "Best food for dogs?"] },
    tl: { name: "Pag-aalaga ng Alagang Hayop", label: "Aso, pusa, kalusugan at pagsasanay", chips: ["Paano sanayin ang tuta?", "Hindi kumakain ang pusa ko", "Pinakamainam na pagkain para sa aso?"] },
    prompt: "You are a friendly pet care advisor. Ask what type and age of pet they have before advising. Always recommend a vet for medical concerns. If the user writes in Tagalog, respond in Tagalog.",
    followUp: "What type of pet do you have and roughly how old are they?",
  },
  {
    id: "legal", icon: "⚖️", bg: "#141414", section: "Personal",
    en: { name: "Legal Questions", label: "Basic rights, documents, advice", chips: ["Rights as an employee?", "How to file a complaint?", "What is a notarized document?"] },
    tl: { name: "Legal na Tanong", label: "Karapatan, dokumento, payo", chips: ["Ano ang karapatan ko bilang empleyado?", "Paano mag-file ng reklamo?", "Ano ang notarized na dokumento?"] },
    prompt: "You are a general legal information guide (NOT a lawyer). Ask what country they are in before giving specific legal info. Always recommend consulting a lawyer for serious matters. If the user writes in Tagalog, respond in Tagalog.",
    followUp: "Are you in the Philippines? And can you briefly describe your situation?",
  },
  {
    id: "electronics", icon: "💻", bg: "#091828", section: "Tech",
    en: { name: "Electronics", label: "Gadgets, devices, repairs", chips: ["My phone battery drains fast", "Best budget laptop 2025", "WiFi keeps disconnecting"] },
    tl: { name: "Electronics", label: "Gadgets, device, pagkukumpuni", chips: ["Mabilis maubos ang baterya", "Pinakamainam na budget laptop", "WiFi laging nangingila"] },
    prompt: "You are an expert electronics technician. Ask about the specific device and symptom before troubleshooting. If the user writes in Tagalog, respond in Tagalog.",
    followUp: "What device are you using — brand and model? And what exactly is happening?",
  },
  {
    id: "coding", icon: "👨‍💻", bg: "#041f14", section: "Tech",
    en: { name: "Coding Help", label: "Debug, learn, build projects", chips: ["Fix my Python error", "Explain what an API is", "How do I center a div?"] },
    tl: { name: "Coding", label: "Debug, matuto, gumawa ng project", chips: ["Ayusin ang Python error", "Ano ang API?", "Paano i-center ang div?"] },
    prompt: "You are a senior software engineer and patient coding mentor. Ask about programming language and experience level first. Show working code examples. If the user writes in Tagalog, respond in Tagalog.",
    followUp: "What programming language are you using? And are you a beginner, intermediate, or advanced developer?",
  },
  {
    id: "research", icon: "📚", bg: "#150f2a", section: "Tech",
    en: { name: "Research Help", label: "Verify facts, summarize topics", chips: ["Is this news reliable?", "Summarize quantum computing", "Explain climate change simply"] },
    tl: { name: "Pananaliksik", label: "I-verify ang impormasyon", chips: ["Totoo ba itong balita?", "I-summarize ang quantum computing", "Ipaliwanag ang climate change"] },
    prompt: "You are a rigorous research assistant. Help verify facts and summarize research. Be objective and flag uncertainty. If the user writes in Tagalog, respond in Tagalog.",
    followUp: "How in-depth do you want this — a simple overview or a detailed breakdown?",
  },
];

export const GENERAL_PROMPT = "You are a helpful, knowledgeable, and friendly general assistant. Answer clearly and warmly. If the user writes in Tagalog, respond in Tagalog.";
